### ISSUE TITLE
Bug Report (Submitted by 5243)

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/shl-trading-cards#251] opened 2024-12-07 18:54 UTC
## Description
When clicking on open a pack and then on the popup "opening cards" are stuck loading until clicking away and opening the pack again. It seems to be on account of the pack graphics "updating" and me clicking too fast.
    
## Reproduction Steps
Go to Open Packs
Directly click on a pack
See the pack graphics update behind the popup
Click open
Wait forever
Click away and open the updated graphics pack
Profit
    
## Operating System
Windows
    
## Browser
Chrome
    
## Device
Desktop

**Comment by luketd** [comment] 2024-12-08 00:43
could not reproduce

**Comment by canadice** [comment] 2024-12-10 08:00
I have reproduced this multiple times. I will try and get a recording

**Comment by canadice** [comment] 2024-12-11 14:49
This recording does not show the issue at hand but a similar one. This time I open the same pack that I already opened but the update of packs and their graphics behind the opened popup still occur which was the issue reported. 

https://drive.google.com/open?id=10Mu8WkYSHTkIb_RkPb6ggQGvD3vke4tY&usp=drive_fs

**Comment by luketd** [comment] 2024-12-13 03:32
> This recording does not show the issue at hand but a similar one. This time I open the same pack that I already opened but the update of packs and their graphics behind the opened popup still occur which was the issue reported.
> 
> https://drive.google.com/open?id=10Mu8WkYSHTkIb_RkPb6ggQGvD3vke4tY&usp=drive_fs

can you open the permissions for that

**Comment by luketd** [comment] 2024-12-14 17:08
Fixed in next update

**Closed by luketd** 2024-12-14 17:08 UTC
Labels: bug
