### ISSUE TITLE
Display number of unique cards on collections page

### ISSUE THREAD

**Issue by esilverm** [GuthrieW/shl-trading-cards#71] opened 2022-03-27 15:07 UTC
As a user I want to be able to see how many cards I have from the complete set of released cards. This addition will give users incentive to keep collecting.

```sql
SELECT count(*)
FROM cards
WHERE image_url IS NOT NULL AND approved=1;
```

**Comment by GuthrieW** [comment] 2023-01-20 00:15
This issue is essentially a duplicate of the collection viewer https://github.com/GuthrieW/shl-trading-cards/issues/83

**Closed by GuthrieW** 2023-01-20 00:15 UTC
Labels: story
